#!/usr/bin/env python3
"""Generate an opt-in 8-slot GH200 profile from an installed Strata JSON config."""
import argparse
import json
from pathlib import Path

def set_argument(argv, flag, value):
    args = list(argv)
    while flag in args:
        idx = args.index(flag)
        if idx + 1 >= len(args):
            raise ValueError(f"{flag} is missing its value")
        del args[idx:idx + 2]
    args += [flag, str(value)]
    return args

def configure(config, slots=8, context=262144):
    if not 1 <= slots <= 8:
        raise ValueError("slots must be 1..8")
    if not 1 <= context <= 262144:
        raise ValueError("context must be 1..262144 (trained limit)")
    out = dict(config)
    args = out.get("args")
    if not isinstance(args, list) or not all(isinstance(x, str) for x in args):
        raise ValueError("expected installed Strata config with string args")
    for flag in ("--pack", "--native"):
        if flag not in args:
            raise ValueError(f"existing config lacks {flag}: install a model first")
    if "--kv" in args:
        k = args.index("--kv")
        if k + 1 >= len(args):
            raise ValueError("--kv is missing its value")
        if args[k + 1] == "k8v4":
            raise ValueError("--kv k8v4 does not support --kv-resident")
    args = set_argument(args, "--max-context", context)
    args = set_argument(args, "--kv", "int8")
    args = set_argument(args, "--kv-resident", min(32768, context))
    args = set_argument(args, "--expert-cache", "auto")
    for flag in ("--batch", "--slots"):
        while flag in args:
            i = args.index(flag)
            if i + 1 >= len(args):
                raise ValueError(f"{flag} is missing its value")
            del args[i:i + 2]
    out["args"] = args
    out["parallel"] = slots
    out["reasoning_budget_tokens"] = 0
    out["reasoning_loop_recovery"] = False
    return out

def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("source", type=Path, help="Strata config generated by setup.sh")
    p.add_argument("--output", type=Path, required=True)
    p.add_argument("--slots", type=int, default=8)
    p.add_argument("--context", type=int, default=262144)
    args = p.parse_args(argv)
    if args.source.resolve() == args.output.resolve():
        p.error("output must differ from input")
    if args.output.exists():
        p.error("output already exists: refusing overwrite")
    config = configure(json.loads(args.source.read_text(encoding="utf-8")), args.slots, args.context)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    print(f"Created {args.output} with {args.slots} slots and {args.context} context tokens")
    print("Qwen Code requests should include reasoning_effort=xhigh.")

if __name__ == "__main__":
    main()
